### ISSUE TITLE
Ne plus utiliser my_putchar

### ISSUE THREAD

**Issue by pouleta** [jaypee-kun/braille-translate#1]
Serieusement, c'est pas bien. Le projet vient d'une colle ?
Refais vite fait une version propre avec les fonctions standard (printf...), parce que quand un CTO va regarder ton profile github il va bien rigoler sinon :)

**Comment by jaypee-kun** [comment]
Ça vient d'une colle. 
Et j'ai viré les my_putchar,etc du coup, merci. :+1:
